sparta-incubating/rchive-back

- .github/workflows/ci.yml
> [#2] feat: github actions CI 구축

- .github/workflows/ci.yml
- src/main/resources/application.yml
> [#2] feat: github action CI 구축 수정

- src/main/java/kr/sparta/rchive/domain/core/service/EducationDataTagCoreService.java
- src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
- src/main/java/kr/sparta/rchive/domain/post/controller/TagCreateRes.java
- src/main/java/kr/sparta/rchive/domain/post/dto/request/TagCreateReq.java
- src/main/java/kr/sparta/rchive/domain/post/dto/request/TagSearchReq.java
- src/main/java/kr/sparta/rchive/domain/post/dto/response/EducationDataRes.java
- src/main/java/kr/sparta/rchive/domain/post/dto/response/PostSearchEducationDataRes.java
- src/main/java/kr/sparta/rchive/domain/post/dto/response/TagSearchRes.java
- src/main/java/kr/sparta/rchive/domain/post/exception/PostCustomExeption.java
- src/main/java/kr/sparta/rchive/domain/post/exception/PostExceptionCode.java
- src/main/java/kr/sparta/rchive/domain/post/repository/EducationDataRepository.java
- src/main/java/kr/sparta/rchive/domain/post/repository/EducationDataTagRepository.java
- src/main/java/kr/sparta/rchive/domain/post/repository/EducationDataTrackRepository.java
- src/main/java/kr/sparta/rchive/domain/post/repository/TagRepository.java
- src/main/java/kr/sparta/rchive/domain/post/response/PostResponseCode.java
- src/main/java/kr/sparta/rchive/domain/post/service/EducationDataService.java
- src/main/java/kr/sparta/rchive/domain/post/service/EducationDataTagService.java
- src/main/java/kr/sparta/rchive/domain/post/service/EducationDataTrackService.java
- src/main/java/kr/sparta/rchive/domain/post/service/TagService.java
- src/main/java/kr/sparta/rchive/global/security/UserDetailsImpl.java
> [#24] Tag 검색 기능

- src/main/java/kr/sparta/rchive/domain/user/entity/Role.java
- src/main/java/kr/sparta/rchive/domain/user/entity/User.java
- src/main/java/kr/sparta/rchive/domain/user/enums/TrackRoleEnum.java
- src/main/java/kr/sparta/rchive/domain/user/enums/UserRoleEnum.java
> [#29] feat: BackOffice 구성하면서 erd 수정

- src/main/java/kr/sparta/rchive/domain/user/entity/Track.java
> [#29] feat: erd 수정

- src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
- src/main/java/kr/sparta/rchive/domain/post/dto/request/TagCreateReq.java
- src/main/java/kr/sparta/rchive/domain/post/dto/request/TagSearchReq.java
- src/main/java/kr/sparta/rchive/domain/post/dto/response/TagCreateRes.java
- src/main/java/kr/sparta/rchive/domain/post/dto/response/TagSearchRes.java
- src/main/java/kr/sparta/rchive/domain/post/entity/Tag.java
- src/main/java/kr/sparta/rchive/domain/post/exception/PostExceptionCode.java
- src/main/java/kr/sparta/rchive/domain/post/repository/TagRepository.java
- src/main/java/kr/sparta/rchive/domain/post/service/TagService.java
> Tag 추가하는 기능 구현

- src/main/java/kr/sparta/rchive/domain/post/entity/EducationData.java
> [#29] feat: 학습자료 erd 수정 

- src/main/java/kr/sparta/rchive/domain/core/service/EducationDataTagCoreService.java
- src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
- src/main/java/kr/sparta/rchive/domain/post/dto/response/PostSearchByTagRes.java
- src/main/java/kr/sparta/rchive/domain/post/entity/EducationDataTag.java
- src/main/java/kr/sparta/rchive/domain/post/entity/EducationDataTrack.java
- src/main/java/kr/sparta/rchive/domain/post/exception/PostExceptionCode.java
- src/main/java/kr/sparta/rchive/domain/post/repository/EducationDataTagRepository.java
- src/main/java/kr/sparta/rchive/domain/post/repository/EducationDataTrackRepository.java
- src/main/java/kr/sparta/rchive/domain/post/response/PostResponseCode.java
- src/main/java/kr/sparta/rchive/domain/post/service/EducationDataService.java
- src/main/java/kr/sparta/rchive/domain/post/service/EducationDataTagService.java
- src/main/java/kr/sparta/rchive/domain/post/service/EducationDataTrackService.java
- src/main/java/kr/sparta/rchive/domain/post/service/TagService.java
- src/main/java/kr/sparta/rchive/domain/user/repository/RoleRepository.java
- src/main/java/kr/sparta/rchive/domain/user/repository/TrackRepository.java
- src/main/java/kr/sparta/rchive/domain/user/repository/UserRepository.java
- src/main/java/kr/sparta/rchive/domain/user/service/RoleService.java
- src/main/java/kr/sparta/rchive/domain/user/service/TrackService.java
- src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
feat(Tag): 태그를 이용하여 게시물 검색하는 기능 추가
> [#25] feat(Tag): 태그를 이용하여 게시물 검색하는 기능 추가

- src/main/java/kr/sparta/rchive/domain/user/controller/UserController.java
- src/main/java/kr/sparta/rchive/domain/user/dto/request/UserLoginReq.java
- src/main/java/kr/sparta/rchive/domain/user/dto/request/UserSignupReq.java
- src/main/java/kr/sparta/rchive/domain/user/entity/User.java
- src/main/java/kr/sparta/rchive/domain/user/exception/UserExceptionCode.java
- src/main/java/kr/sparta/rchive/domain/user/response/UserResponseCode.java
- src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
- src/main/java/kr/sparta/rchive/global/config/WebSecurityConfig.java
- src/main/java/kr/sparta/rchive/global/security/JwtAuthorizationFilter.java
- src/main/java/kr/sparta/rchive/global/security/JwtUtil.java
- src/main/java/kr/sparta/rchive/global/security/LoginFilter.java
- src/main/java/kr/sparta/rchive/global/security/UserDetailsImpl.java
- src/main/java/kr/sparta/rchive/global/security/UserDetailsServiceImpl.java
- src/main/resources/application.yml
> 회원가입 PR 리뷰 적용

- src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
- src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
- src/main/java/kr/sparta/rchive/domain/post/dto/request/PostCreateReq.java
- src/main/java/kr/sparta/rchive/domain/post/dto/response/PostCreateRes.java
- src/main/java/kr/sparta/rchive/domain/post/entity/Content.java
- src/main/java/kr/sparta/rchive/domain/post/entity/Post.java
- src/main/java/kr/sparta/rchive/domain/post/repository/ContentRepository.java
- src/main/java/kr/sparta/rchive/domain/post/repository/TagRepository.java
- src/main/java/kr/sparta/rchive/domain/post/response/PostResponseCode.java
- src/main/java/kr/sparta/rchive/domain/post/service/ContentService.java
- src/main/java/kr/sparta/rchive/domain/post/service/PostService.java
- src/main/java/kr/sparta/rchive/domain/post/service/PostTagService.java
- src/main/java/kr/sparta/rchive/domain/post/service/PostTrackService.java
- src/main/java/kr/sparta/rchive/domain/post/service/TagService.java
- src/main/java/kr/sparta/rchive/domain/user/entity/Track.java
- src/main/java/kr/sparta/rchive/domain/user/repository/TrackRepository.java
- src/main/java/kr/sparta/rchive/domain/user/service/TrackService.java
- src/main/java/kr/sparta/rchive/global/config/WebSecurityConfig.java
- src/main/java/kr/sparta/rchive/global/redis/RedisService.java
> [#43] Post 생성 기능 추가

- src/main/java/kr/sparta/rchive/domain/user/controller/UserController.java
- src/main/java/kr/sparta/rchive/domain/user/entity/User.java
- src/main/java/kr/sparta/rchive/domain/user/exception/UserExceptionCode.java
- src/main/java/kr/sparta/rchive/domain/user/repository/UserRepository.java
- src/main/java/kr/sparta/rchive/domain/user/response/UserResponseCode.java
- src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
- src/main/java/kr/sparta/rchive/global/config/WebSecurityConfig.java
- src/main/java/kr/sparta/rchive/global/execption/GlobalCustomException.java
- src/main/java/kr/sparta/rchive/global/execption/GlobalExceptionCode.java
- src/main/java/kr/sparta/rchive/global/execption/GlobalExceptionHandler.java
- src/main/java/kr/sparta/rchive/global/redis/RedisService.java
- src/main/java/kr/sparta/rchive/global/security/JwtAuthorizationFilter.java
- src/main/java/kr/sparta/rchive/global/security/JwtUtil.java
- src/main/java/kr/sparta/rchive/global/security/LoginFilter.java
- src/main/java/kr/sparta/rchive/global/security/UserDetailsServiceImpl.java
> [#42] User: 리프레시 토큰 관련 구현

- src/main/java/kr/sparta/rchive/domain/user/controller/UserController.java
- src/main/java/kr/sparta/rchive/domain/user/response/UserResponseCode.java
- src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
- src/main/java/kr/sparta/rchive/global/redis/RedisService.java
> [#46] User: 로그아웃

- src/main/java/kr/sparta/rchive/domain/user/controller/UserController.java
- src/main/java/kr/sparta/rchive/domain/user/entity/User.java
- src/main/java/kr/sparta/rchive/domain/user/response/UserResponseCode.java
- src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
- src/main/java/kr/sparta/rchive/global/security/JwtUtil.java
> [#48] User: 회원탈퇴

- src/main/java/kr/sparta/rchive/domain/user/controller/UserController.java
- src/main/java/kr/sparta/rchive/domain/user/response/UserResponseCode.java
- src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
> [#53] User: 이메일 중복 여부 조회 구현

- src/main/java/kr/sparta/rchive/domain/user/controller/UserController.java
- src/main/java/kr/sparta/rchive/domain/user/response/UserResponseCode.java
- src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
> [#54] User: 닉네임 중복 여부 조회 구현

- src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
- src/main/java/kr/sparta/rchive/domain/core/service/UserTrackRoleCoreService.java
- src/main/java/kr/sparta/rchive/domain/post/dto/request/PostCreateReq.java
- src/main/java/kr/sparta/rchive/domain/post/service/PostTrackService.java
- src/main/java/kr/sparta/rchive/domain/user/controller/RoleController.java
- src/main/java/kr/sparta/rchive/domain/user/dto/request/RoleRequestReq.java
- src/main/java/kr/sparta/rchive/domain/user/entity/Track.java
- src/main/java/kr/sparta/rchive/domain/user/enums/TrackNameEnum.java
- src/main/java/kr/sparta/rchive/domain/user/repository/TrackRepository.java
- src/main/java/kr/sparta/rchive/domain/user/response/UserResponseCode.java
- src/main/java/kr/sparta/rchive/domain/user/service/RoleService.java
- src/main/java/kr/sparta/rchive/domain/user/service/TrackService.java
- src/main/java/kr/sparta/rchive/global/config/WebSecurityConfig.java
> [#57] Role: 내 권한(트랙 및 기수) 요청

- src/main/java/kr/sparta/rchive/domain/post/entity/Post.java
- src/main/java/kr/sparta/rchive/domain/user/controller/UserController.java
- src/main/java/kr/sparta/rchive/domain/user/entity/Track.java
- src/main/java/kr/sparta/rchive/domain/user/entity/User.java
- src/main/java/kr/sparta/rchive/global/security/JwtUtil.java
> [#67] User: 회원가입 수정

- src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
- src/main/java/kr/sparta/rchive/domain/post/entity/Post.java
- src/main/java/kr/sparta/rchive/domain/post/entity/Tag.java
- src/main/java/kr/sparta/rchive/domain/post/response/PostResponseCode.java
- src/main/java/kr/sparta/rchive/domain/post/service/PostService.java
- src/main/java/kr/sparta/rchive/domain/user/entity/Track.java
> [#50] Post: 게시물 관리 삭제 기능 추가

- src/main/java/kr/sparta/rchive/domain/user/controller/UserController.java
> [#73] User: 이메일 중복, 닉네임 중복 수정

- src/main/java/kr/sparta/rchive/domain/core/service/UserTrackRoleCoreService.java
- src/main/java/kr/sparta/rchive/domain/user/controller/RoleController.java
- src/main/java/kr/sparta/rchive/domain/user/dto/response/RoleGetTrackNameListReq.java
- src/main/java/kr/sparta/rchive/domain/user/response/UserResponseCode.java
- src/main/java/kr/sparta/rchive/domain/user/service/TrackService.java
> [#62] Role: 트랙명 조회

- src/main/java/kr/sparta/rchive/domain/user/controller/RoleController.java
- src/main/java/kr/sparta/rchive/domain/user/dto/response/RoleGetTrackNameListRes.java
- src/main/java/kr/sparta/rchive/domain/user/dto/response/RoleGetTrackPeriodListRes.java
- src/main/java/kr/sparta/rchive/domain/user/repository/TrackRepository.java
- src/main/java/kr/sparta/rchive/domain/user/response/UserResponseCode.java
- src/main/java/kr/sparta/rchive/domain/user/service/TrackService.java
> [#63] Role: 트랙의 기수 조회

- src/main/java/kr/sparta/rchive/global/config/WebMvcConfig.java
> [#72] CORS 설정

- src/main/java/kr/sparta/rchive/domain/user/controller/RoleController.java
- src/main/java/kr/sparta/rchive/domain/user/repository/RoleRepository.java
- src/main/java/kr/sparta/rchive/domain/user/response/UserResponseCode.java
- src/main/java/kr/sparta/rchive/domain/user/service/RoleService.java
- src/main/java/kr/sparta/rchive/domain/user/service/TrackService.java
> [#79] Role: 권한 신청 여부 조회 - 최초 로그인

- src/main/java/kr/sparta/rchive/domain/user/controller/RoleController.java
- src/main/java/kr/sparta/rchive/domain/user/controller/UserController.java
- src/main/java/kr/sparta/rchive/domain/user/exception/RoleCustomException.java
- src/main/java/kr/sparta/rchive/domain/user/exception/RoleExceptionCode.java
- src/main/java/kr/sparta/rchive/domain/user/repository/RoleRepository.java
- src/main/java/kr/sparta/rchive/domain/user/response/RoleResponseCode.java
- src/main/java/kr/sparta/rchive/domain/user/service/RoleService.java
- src/main/java/kr/sparta/rchive/global/response/CommonResponseDto.java
- src/main/java/kr/sparta/rchive/global/response/GlobalResponseCode.java
- src/main/java/kr/sparta/rchive/global/response/ResponseCode.java
> [#64] Role: 권한 신청 결과 조회

- src/main/java/kr/sparta/rchive/domain/core/service/UserTrackRoleCoreService.java
- src/main/java/kr/sparta/rchive/domain/user/controller/RoleController.java
- src/main/java/kr/sparta/rchive/domain/user/dto/response/RoleGetLastSelectRoleRes.java
- src/main/java/kr/sparta/rchive/domain/user/exception/RoleExceptionCode.java
- src/main/java/kr/sparta/rchive/domain/user/repository/RoleRepository.java
- src/main/java/kr/sparta/rchive/domain/user/response/RoleResponseCode.java
- src/main/java/kr/sparta/rchive/domain/user/service/RoleService.java
- src/main/java/kr/sparta/rchive/global/config/WebSecurityConfig.java
> [#85] Role: 마지막에 선택한 권한 조회 - 백오피스

- src/main/java/kr/sparta/rchive/domain/user/dto/request/UserSignupReq.java
- src/main/java/kr/sparta/rchive/domain/user/entity/User.java
- src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
> [#90] User: username 추가

- src/main/java/kr/sparta/rchive/domain/comment/dto/response/CommentRes.java
- src/main/java/kr/sparta/rchive/domain/comment/repository/CommentRepository.java
- src/main/java/kr/sparta/rchive/domain/comment/service/CommentService.java
- src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
- src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
- src/main/java/kr/sparta/rchive/domain/post/dto/response/PostGetCategoryPostRes.java
- src/main/java/kr/sparta/rchive/domain/post/dto/response/PostGetSinglePostRes.java
- src/main/java/kr/sparta/rchive/domain/post/entity/Tag.java
- src/main/java/kr/sparta/rchive/domain/post/repository/PostRepository.java
- src/main/java/kr/sparta/rchive/domain/post/repository/PostTagRepository.java
- src/main/java/kr/sparta/rchive/domain/post/repository/TagRepository.java
- src/main/java/kr/sparta/rchive/domain/post/response/PostResponseCode.java
- src/main/java/kr/sparta/rchive/domain/post/service/ContentService.java
- src/main/java/kr/sparta/rchive/domain/post/service/PostService.java
- src/main/java/kr/sparta/rchive/domain/post/service/PostTagService.java
- src/main/java/kr/sparta/rchive/domain/post/service/TagService.java
- src/main/java/kr/sparta/rchive/domain/user/exception/RoleExceptionCode.java
- src/main/java/kr/sparta/rchive/domain/user/repository/RoleRepository.java
- src/main/java/kr/sparta/rchive/domain/user/service/RoleService.java
카테고리 별 게시글 목록 조회 기능 추가
게시글 단건 조회 기능
> [#83, #77] 카테고리 별 게시글 목록 조회 기능 추가 / 게시글 단건 조회 기능 추가

- src/main/java/kr/sparta/rchive/domain/backoffice/controller/BackofficeController.java
- src/main/java/kr/sparta/rchive/domain/backoffice/respoonse/BackofficeResponseCode.java
- src/main/java/kr/sparta/rchive/domain/user/controller/ProfileController.java
- src/main/java/kr/sparta/rchive/domain/user/controller/RoleController.java
- src/main/java/kr/sparta/rchive/domain/user/response/RoleResponseCode.java
- src/main/java/kr/sparta/rchive/global/config/WebSecurityConfig.java
> [#94] Backoffice: API 이동

- src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
- src/main/java/kr/sparta/rchive/domain/post/entity/Post.java
- src/main/java/kr/sparta/rchive/domain/post/response/PostResponseCode.java
- src/main/java/kr/sparta/rchive/domain/post/service/PostService.java
> [#97] Post: 게시물 공개 여부 상태 공개로 변경하는 로직 추가

- src/main/java/kr/sparta/rchive/domain/user/controller/ProfileController.java
- src/main/java/kr/sparta/rchive/domain/user/dto/request/ProfileUpdatePasswordReq.java
- src/main/java/kr/sparta/rchive/domain/user/entity/User.java
- src/main/java/kr/sparta/rchive/domain/user/exception/UserExceptionCode.java
- src/main/java/kr/sparta/rchive/domain/user/response/ProfileResponseCode.java
- src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
> [#89] Profile: 비밀번호 변경

- src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
- src/main/java/kr/sparta/rchive/domain/post/entity/Post.java
- src/main/java/kr/sparta/rchive/domain/post/response/PostResponseCode.java
- src/main/java/kr/sparta/rchive/domain/post/service/PostService.java
> [#99] Post: 게시물 공개 여부 상태 비공개로 변경하는 로직 추가

- src/main/java/kr/sparta/rchive/domain/backoffice/controller/BackofficeController.java
- src/main/java/kr/sparta/rchive/domain/backoffice/respoonse/BackofficeResponseCode.java
- src/main/java/kr/sparta/rchive/domain/core/service/UserTrackRoleCoreService.java
- src/main/java/kr/sparta/rchive/domain/user/dto/request/RoleRequestListReq.java
- src/main/java/kr/sparta/rchive/domain/user/entity/Role.java
- src/main/java/kr/sparta/rchive/domain/user/exception/RoleExceptionCode.java
- src/main/java/kr/sparta/rchive/domain/user/repository/RoleRepository.java
- src/main/java/kr/sparta/rchive/domain/user/repository/UserRepository.java
- src/main/java/kr/sparta/rchive/domain/user/service/RoleService.java
- src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
> [#102] BackOffice: 유저의 트랙 권한 수락

- src/main/java/kr/sparta/rchive/domain/backoffice/controller/BackofficeController.java
- src/main/java/kr/sparta/rchive/domain/backoffice/respoonse/BackofficeResponseCode.java
- src/main/java/kr/sparta/rchive/domain/core/service/UserTrackRoleCoreService.java
- src/main/java/kr/sparta/rchive/domain/user/entity/Role.java
- src/main/java/kr/sparta/rchive/domain/user/service/RoleService.java
> [#103] BackOffice: 유저의 트랙 권한 거절

- src/main/java/kr/sparta/rchive/domain/core/service/UserTrackRoleCoreService.java
- src/main/java/kr/sparta/rchive/domain/user/repository/RoleRepository.java
- src/main/java/kr/sparta/rchive/domain/user/service/RoleService.java
유저의 트랙 권한 수락 - auth approve 제외하고 삭제
> [#106] BackOffice: 유저의 트랙 권한 수락 - auth approve 제외하고 삭제

- build.gradle
- src/main/java/kr/sparta/rchive/domain/backoffice/controller/BackofficeController.java
- src/main/java/kr/sparta/rchive/domain/backoffice/respoonse/BackofficeResponseCode.java
- src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
- src/main/java/kr/sparta/rchive/domain/post/dto/PostSearchInfo.java
- src/main/java/kr/sparta/rchive/domain/post/dto/response/PostSearchBackOfficeRes.java
- src/main/java/kr/sparta/rchive/domain/post/repository/PostRepository.java
- src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustom.java
- src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustomImpl.java
- src/main/java/kr/sparta/rchive/domain/post/service/PostService.java
- src/main/java/kr/sparta/rchive/global/config/QueryDslConfig.java
> [#96] BackOffice: 매니저가 게시물 검색하는 기능 추가

- build.gradle
- src/main/java/kr/sparta/rchive/domain/backoffice/controller/BackofficeController.java
- src/main/java/kr/sparta/rchive/domain/backoffice/respoonse/BackofficeResponseCode.java
- src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
- src/main/java/kr/sparta/rchive/domain/post/dto/PostSearchInfo.java
- src/main/java/kr/sparta/rchive/domain/post/dto/response/PostSearchBackOfficeRes.java
- src/main/java/kr/sparta/rchive/domain/post/repository/PostRepository.java
- src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustom.java
- src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustomImpl.java
- src/main/java/kr/sparta/rchive/domain/post/service/PostService.java
- src/main/java/kr/sparta/rchive/global/config/QueryDslConfig.java
> [#110] Post: 카테고리 별 게시물 조회 기능 성능 개선

- src/main/java/kr/sparta/rchive/domain/backoffice/controller/BackofficeController.java
- src/main/java/kr/sparta/rchive/domain/core/service/UserTrackRoleCoreService.java
- src/main/java/kr/sparta/rchive/domain/user/dto/request/UserSignupReq.java
- src/main/java/kr/sparta/rchive/domain/user/dto/response/UserRes.java
- src/main/java/kr/sparta/rchive/domain/user/entity/User.java
- src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
> [#115] User: 프로필이미지 추가

- src/main/java/kr/sparta/rchive/domain/user/controller/ProfileController.java
- src/main/java/kr/sparta/rchive/domain/user/dto/request/ProfileUpdateReq.java
- src/main/java/kr/sparta/rchive/domain/user/entity/User.java
- src/main/java/kr/sparta/rchive/domain/user/response/ProfileResponseCode.java
- src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
> [#88] Profile: 프로필 수정

- src/main/java/kr/sparta/rchive/domain/backoffice/controller/BackofficeController.java
- src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
- src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
- src/main/java/kr/sparta/rchive/domain/post/dto/TagInfo.java
- src/main/java/kr/sparta/rchive/domain/post/dto/response/PostSearchBackOfficeRes.java
- src/main/java/kr/sparta/rchive/domain/post/repository/PostRepository.java
- src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustom.java
- src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustomImpl.java
- src/main/java/kr/sparta/rchive/domain/post/service/PostService.java
> [#113] 백오피스: 백오피스에서의 게시물 조회 기능 수정

- src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
- src/main/java/kr/sparta/rchive/domain/post/dto/response/PostGetSinglePostRes.java
- src/main/java/kr/sparta/rchive/domain/post/entity/Content.java
- src/main/java/kr/sparta/rchive/domain/post/repository/PostRepository.java
- src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustomImpl.java
- src/main/java/kr/sparta/rchive/domain/post/service/ContentService.java
- src/main/java/kr/sparta/rchive/domain/post/service/PostService.java
> [#111] Post: 게시물 단건 조회 성능 개선 및 리팩토링

- src/main/java/kr/sparta/rchive/domain/backoffice/controller/BackofficeController.java
- src/main/java/kr/sparta/rchive/domain/backoffice/respoonse/BackofficeResponseCode.java
- src/main/java/kr/sparta/rchive/domain/core/service/UserTrackRoleCoreService.java
- src/main/java/kr/sparta/rchive/domain/user/dto/response/RoleGetTrackRoleRequestCountRes.java
- src/main/java/kr/sparta/rchive/domain/user/exception/RoleExceptionCode.java
- src/main/java/kr/sparta/rchive/domain/user/repository/RoleRepository.java
- src/main/java/kr/sparta/rchive/domain/user/service/RoleService.java
> [#118] BackOffice: 유저의 트랙 권한 신청 건수

- src/main/java/kr/sparta/rchive/domain/user/controller/UserController.java
- src/main/java/kr/sparta/rchive/domain/user/dto/request/UserSignupReq.java
- src/main/java/kr/sparta/rchive/domain/user/entity/User.java
> [#121] User: 유저 밸리데이션

- src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
- src/main/java/kr/sparta/rchive/domain/post/dto/request/PostCreateReq.java
- src/main/java/kr/sparta/rchive/domain/post/entity/Post.java
- src/main/java/kr/sparta/rchive/domain/post/service/PostService.java
- src/main/java/kr/sparta/rchive/global/config/WebSecurityConfig.java
- src/main/java/kr/sparta/rchive/global/execption/GlobalExceptionCode.java
- src/main/java/kr/sparta/rchive/global/response/GlobalResponseCode.java
- src/main/java/kr/sparta/rchive/global/s3/S3ImageController.java
- src/main/java/kr/sparta/rchive/global/s3/S3ImageService.java
> [#130] S3: 썸네일 업로드 기능 추가

- src/main/java/kr/sparta/rchive/domain/backoffice/controller/BackofficeController.java
- src/main/java/kr/sparta/rchive/domain/backoffice/respoonse/BackofficeResponseCode.java
- src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
- src/main/java/kr/sparta/rchive/domain/core/service/UserTrackRoleCoreService.java
- src/main/java/kr/sparta/rchive/domain/post/service/PostService.java
- src/main/java/kr/sparta/rchive/domain/user/dto/response/RoleGetTrackRoleRequestListRes.java
- src/main/java/kr/sparta/rchive/domain/user/exception/RoleExceptionCode.java
- src/main/java/kr/sparta/rchive/domain/user/repository/RoleRepository.java
- src/main/java/kr/sparta/rchive/domain/user/repository/RoleRepositoryCustom.java
- src/main/java/kr/sparta/rchive/domain/user/repository/RoleRepositoryCustomImpl.java
- src/main/java/kr/sparta/rchive/domain/user/service/RoleService.java
> [#133] BackOffice: 유저의 트랙 권한 신청 목록 조회 

- src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
- src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
- src/main/java/kr/sparta/rchive/domain/post/dto/response/PostGetCategoryPostRes.java
- src/main/java/kr/sparta/rchive/domain/post/dto/response/PostSearchBackOfficeRes.java
- src/main/java/kr/sparta/rchive/domain/post/dto/response/PostSearchByTagRes.java
- src/main/java/kr/sparta/rchive/domain/post/dto/response/PostSearchRes.java
> [#132] 게시물 검색 시 썸네일이 보이는 기능 추가

- src/main/java/kr/sparta/rchive/domain/backoffice/controller/BackofficeController.java
- src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
- src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
- src/main/java/kr/sparta/rchive/domain/post/dto/request/PostCreateReq.java
- src/main/java/kr/sparta/rchive/domain/post/dto/request/PostModifyReq.java
- src/main/java/kr/sparta/rchive/domain/post/dto/response/PostGetCategoryPostRes.java
- src/main/java/kr/sparta/rchive/domain/post/dto/response/PostSearchBackOfficeRes.java
- src/main/java/kr/sparta/rchive/domain/post/dto/response/PostSearchByTagRes.java
- src/main/java/kr/sparta/rchive/domain/post/dto/response/PostSearchRes.java
- src/main/java/kr/sparta/rchive/domain/post/entity/Post.java
- src/main/java/kr/sparta/rchive/domain/post/exception/PostExceptionCode.java
- src/main/java/kr/sparta/rchive/domain/post/service/PostService.java
> [#139] 게시물 조회 및 수정 삭제 권한 로직 수정

- src/main/java/kr/sparta/rchive/domain/backoffice/controller/BackofficeController.java
- src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
- src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
- src/main/java/kr/sparta/rchive/domain/post/dto/request/PostCreateReq.java
- src/main/java/kr/sparta/rchive/domain/post/dto/request/PostModifyReq.java
- src/main/java/kr/sparta/rchive/domain/post/dto/response/PostGetCategoryPostRes.java
- src/main/java/kr/sparta/rchive/domain/post/dto/response/PostSearchBackOfficeRes.java
- src/main/java/kr/sparta/rchive/domain/post/dto/response/PostSearchByTagRes.java
- src/main/java/kr/sparta/rchive/domain/post/dto/response/PostSearchRes.java
- src/main/java/kr/sparta/rchive/domain/post/entity/Post.java
- src/main/java/kr/sparta/rchive/domain/post/exception/PostExceptionCode.java
- src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustom.java
- src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustomImpl.java
- src/main/java/kr/sparta/rchive/domain/post/service/PostService.java
- src/main/java/kr/sparta/rchive/global/config/WebSecurityConfig.java
- src/main/java/kr/sparta/rchive/global/execption/GlobalExceptionCode.java
- src/main/java/kr/sparta/rchive/global/response/GlobalResponseCode.java
- src/main/java/kr/sparta/rchive/global/s3/S3ImageController.java
- src/main/java/kr/sparta/rchive/global/s3/S3ImageService.java
> [#137] S3: 업로드한 썸네일 삭제하는 로직 추가

- src/main/java/kr/sparta/rchive/domain/core/service/UserTrackRoleCoreService.java
- src/main/java/kr/sparta/rchive/domain/user/controller/RoleController.java
- src/main/java/kr/sparta/rchive/domain/user/dto/response/RoleRes.java
- src/main/java/kr/sparta/rchive/domain/user/repository/TrackRepository.java
- src/main/java/kr/sparta/rchive/domain/user/response/RoleResponseCode.java
- src/main/java/kr/sparta/rchive/domain/user/service/RoleService.java
- src/main/java/kr/sparta/rchive/domain/user/service/TrackService.java
> [#143] Role: 내 권한(트랙 및 기수) 조회

- src/main/java/kr/sparta/rchive/domain/bookmark/repository/BookmarkRepository.java
- src/main/java/kr/sparta/rchive/domain/bookmark/service/BookmarkService.java
- src/main/java/kr/sparta/rchive/domain/core/service/PostBookmarkCoreService.java
- src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
- src/main/java/kr/sparta/rchive/domain/post/exception/PostExceptionCode.java
- src/main/java/kr/sparta/rchive/domain/post/response/PostResponseCode.java
> [#147] Bookmark: 북마크 추가하고 삭제하는 기능 추가

- .github/workflows/ci.yml
> [#149] CI: CI 속도향상

- src/main/java/kr/sparta/rchive/domain/bookmark/service/BookmarkService.java
- src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
- src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
- src/main/java/kr/sparta/rchive/domain/post/exception/PostExceptionCode.java
- src/main/java/kr/sparta/rchive/domain/post/response/PostResponseCode.java
- src/main/java/kr/sparta/rchive/domain/post/service/PostService.java
- src/main/java/kr/sparta/rchive/domain/post/service/TagService.java
- src/main/java/kr/sparta/rchive/domain/user/controller/ProfileController.java
- src/main/java/kr/sparta/rchive/domain/user/controller/RoleController.java
- src/main/java/kr/sparta/rchive/domain/user/controller/UserController.java
- src/main/java/kr/sparta/rchive/domain/user/exception/RoleExceptionCode.java
- src/main/java/kr/sparta/rchive/domain/user/exception/TrackCustomException.java
- src/main/java/kr/sparta/rchive/domain/user/exception/TrackExceptionCode.java
- src/main/java/kr/sparta/rchive/domain/user/exception/UserExceptionCode.java
- src/main/java/kr/sparta/rchive/domain/user/response/ProfileResponseCode.java
- src/main/java/kr/sparta/rchive/domain/user/response/RoleResponseCode.java
- src/main/java/kr/sparta/rchive/domain/user/response/UserResponseCode.java
- src/main/java/kr/sparta/rchive/domain/user/service/TrackService.java
- src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
- src/main/java/kr/sparta/rchive/global/execption/GlobalExceptionCode.java
- src/main/java/kr/sparta/rchive/global/response/GlobalResponseCode.java
- src/main/java/kr/sparta/rchive/global/s3/S3ImageController.java
> [#153] refactor: exception, response 코드 맞추기

- src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
- src/main/java/kr/sparta/rchive/domain/core/service/UserTrackRoleCoreService.java
- src/main/java/kr/sparta/rchive/domain/user/controller/RoleController.java
- src/main/java/kr/sparta/rchive/domain/user/dto/request/RoleSelectRoleReq.java
- src/main/java/kr/sparta/rchive/domain/user/dto/response/RoleRes.java
- src/main/java/kr/sparta/rchive/domain/user/exception/RoleExceptionCode.java
- src/main/java/kr/sparta/rchive/domain/user/response/RoleResponseCode.java
- src/main/java/kr/sparta/rchive/domain/user/service/RoleService.java
- src/main/java/kr/sparta/rchive/global/redis/RedisConfig.java
- src/main/java/kr/sparta/rchive/global/redis/RedisService.java
- src/main/java/kr/sparta/rchive/global/redis/RedisUtil.java
> [#146] Role: 내 권한(트랙 및 기수) 선택

- src/main/java/kr/sparta/rchive/domain/backoffice/controller/BackofficeController.java
- src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
- src/main/java/kr/sparta/rchive/domain/core/service/UserTrackRoleCoreService.java
- src/main/java/kr/sparta/rchive/domain/user/controller/RoleController.java
- src/main/java/kr/sparta/rchive/domain/user/dto/response/RoleGetLastSelectRoleRes.java
- src/main/java/kr/sparta/rchive/domain/user/exception/RoleExceptionCode.java
- src/main/java/kr/sparta/rchive/domain/user/response/RoleResponseCode.java
- src/main/java/kr/sparta/rchive/domain/user/service/RoleService.java
- src/main/java/kr/sparta/rchive/global/redis/RedisService.java
> [#152] Role: 마지막 선택한 권한 조회 - 유저페이지

- src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
- src/main/java/kr/sparta/rchive/domain/core/service/UserTrackRoleCoreService.java
- src/main/java/kr/sparta/rchive/domain/user/exception/RoleExceptionCode.java
- src/main/java/kr/sparta/rchive/domain/user/service/RoleService.java
> [#156] 에러 코드 수정

- src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
- src/main/java/kr/sparta/rchive/domain/user/controller/UserController.java
- src/main/java/kr/sparta/rchive/domain/user/exception/TrackExceptionCode.java
> [#166] fix(Post): 게시물과 트랙이 일치하는지 체크하는 로직 추가

- src/main/java/kr/sparta/rchive/domain/post/exception/PostExceptionCode.java
- src/main/java/kr/sparta/rchive/domain/user/controller/UserController.java
- src/main/java/kr/sparta/rchive/domain/user/exception/RoleExceptionCode.java
- src/main/java/kr/sparta/rchive/domain/user/exception/TrackExceptionCode.java
- src/main/java/kr/sparta/rchive/domain/user/exception/UserExceptionCode.java
- src/main/java/kr/sparta/rchive/global/config/SwaggerConfig.java
- src/main/java/kr/sparta/rchive/global/config/SwaggerExampleHolder.java
- src/main/java/kr/sparta/rchive/global/execption/ApiExceptionCodeExample.java
- src/main/java/kr/sparta/rchive/global/execption/ExceptionCode.java
- src/main/java/kr/sparta/rchive/global/execption/ExceptionController.java
- src/main/java/kr/sparta/rchive/global/execption/ExceptionReason.java
- src/main/java/kr/sparta/rchive/global/execption/ExceptionResponse.java
- src/main/java/kr/sparta/rchive/global/execption/ExplainException.java
- src/main/java/kr/sparta/rchive/global/execption/GlobalExceptionCode.java
> [#159] Swagger: 에러 리스트 작성

- src/main/java/kr/sparta/rchive/domain/core/service/UserTrackRoleCoreService.java
- src/main/java/kr/sparta/rchive/domain/user/controller/ProfileController.java
- src/main/java/kr/sparta/rchive/domain/user/controller/RoleController.java
- src/main/java/kr/sparta/rchive/domain/user/dto/request/RoleReq.java
- src/main/java/kr/sparta/rchive/domain/user/exception/RoleExceptionCode.java
- src/main/java/kr/sparta/rchive/domain/user/response/ProfileResponseCode.java
- src/main/java/kr/sparta/rchive/domain/user/service/RoleService.java
- src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
> [#163] Profile: 내 프로필 조회

- src/main/java/kr/sparta/rchive/domain/user/controller/ProfileController.java
- src/main/java/kr/sparta/rchive/domain/user/dto/request/ProfileUpdatePhoneReq.java
- src/main/java/kr/sparta/rchive/domain/user/entity/User.java
- src/main/java/kr/sparta/rchive/domain/user/response/ProfileResponseCode.java
- src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
> [#164] Profile: 휴대폰 번호 변경

- src/main/java/kr/sparta/rchive/domain/backoffice/controller/BackofficeController.java
- src/main/java/kr/sparta/rchive/domain/core/service/UserTrackRoleCoreService.java
- src/main/java/kr/sparta/rchive/domain/user/enums/OrderRoleListEnum.java
- src/main/java/kr/sparta/rchive/domain/user/repository/RoleRepositoryCustom.java
- src/main/java/kr/sparta/rchive/domain/user/repository/RoleRepositoryCustomImpl.java
- src/main/java/kr/sparta/rchive/domain/user/service/RoleService.java
> [#171] BackOffice: 권한 신청 목록 조회 - 정렬

- src/main/java/kr/sparta/rchive/global/config/SwaggerConfig.java
- src/main/java/kr/sparta/rchive/global/execption/ExceptionResponse.java
> [#173] Swagger: 에러 문서화

- src/main/java/kr/sparta/rchive/domain/backoffice/controller/BackofficeController.java
- src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
- src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
- src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustom.java
- src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustomImpl.java
- src/main/java/kr/sparta/rchive/domain/post/response/PostResponseCode.java
- src/main/java/kr/sparta/rchive/domain/post/service/PostService.java
> [#182] Tutor: 튜터 추가로 인한 백오피스 게시물 관련 수정

- src/main/java/kr/sparta/rchive/domain/backoffice/controller/BackofficeController.java
- src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
- src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
- src/main/java/kr/sparta/rchive/domain/post/controller/TutorRes.java
- src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustom.java
- src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustomImpl.java
- src/main/java/kr/sparta/rchive/domain/post/repository/TutorRepository.java
- src/main/java/kr/sparta/rchive/domain/post/response/PostResponseCode.java
- src/main/java/kr/sparta/rchive/domain/post/service/PostService.java
- src/main/java/kr/sparta/rchive/domain/post/service/TutorService.java
> [#180] Tutor: 튜터를 검색해오는 기능 추가

- src/main/java/kr/sparta/rchive/domain/backoffice/controller/BackofficeController.java
- src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
- src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
- src/main/java/kr/sparta/rchive/domain/post/controller/TutorRes.java
- src/main/java/kr/sparta/rchive/domain/post/dto/response/PostGetSinglePostRes.java
- src/main/java/kr/sparta/rchive/domain/post/entity/Tutor.java
- src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustom.java
- src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustomImpl.java
- src/main/java/kr/sparta/rchive/domain/post/repository/TutorRepository.java
- src/main/java/kr/sparta/rchive/domain/post/response/PostResponseCode.java
- src/main/java/kr/sparta/rchive/domain/post/service/PostService.java
- src/main/java/kr/sparta/rchive/domain/post/service/TutorService.java
> [#178] Tutor: 유저가 게시물 조회할 때 변경되는 사항 적용

- src/main/java/kr/sparta/rchive/domain/backoffice/controller/BackofficeController.java
- src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
- src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
- src/main/java/kr/sparta/rchive/domain/post/controller/TutorRes.java
- src/main/java/kr/sparta/rchive/domain/post/dto/request/PostCreateReq.java
- src/main/java/kr/sparta/rchive/domain/post/dto/request/PostUpdateReq.java
- src/main/java/kr/sparta/rchive/domain/post/dto/response/PostGetSinglePostRes.java
- src/main/java/kr/sparta/rchive/domain/post/entity/Post.java
- src/main/java/kr/sparta/rchive/domain/post/entity/Tutor.java
- src/main/java/kr/sparta/rchive/domain/post/exception/PostExceptionCode.java
- src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustom.java
- src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustomImpl.java
- src/main/java/kr/sparta/rchive/domain/post/repository/TutorRepository.java
- src/main/java/kr/sparta/rchive/domain/post/response/PostResponseCode.java
- src/main/java/kr/sparta/rchive/domain/post/service/PostService.java
- src/main/java/kr/sparta/rchive/domain/post/service/TutorService.java
> [#176] Tutor: 게시물 수정 관련 튜터 추가

- src/main/java/kr/sparta/rchive/domain/bookmark/repository/BookmarkRepository.java
- src/main/java/kr/sparta/rchive/domain/bookmark/repository/BookmarkRepositoryCustom.java
- src/main/java/kr/sparta/rchive/domain/bookmark/repository/BookmarkRepositoryCustomImpl.java
- src/main/java/kr/sparta/rchive/domain/bookmark/service/BookmarkService.java
- src/main/java/kr/sparta/rchive/domain/core/service/PostBookmarkCoreService.java
- src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
- src/main/java/kr/sparta/rchive/domain/post/dto/response/PostGetCategoryPostRes.java
- src/main/java/kr/sparta/rchive/domain/post/dto/response/PostGetSinglePostRes.java
- src/main/java/kr/sparta/rchive/domain/post/dto/response/PostRes.java
- src/main/java/kr/sparta/rchive/domain/post/dto/response/PostSearchByTagRes.java
- src/main/java/kr/sparta/rchive/domain/post/dto/response/PostSearchRes.java
- src/main/java/kr/sparta/rchive/domain/user/controller/ProfileController.java
- src/main/java/kr/sparta/rchive/domain/user/response/ProfileResponseCode.java
> [#189] Bookmark: 북마크 해놓은 게시물 프로필에서 확인하는 기능 추가

- src/main/java/kr/sparta/rchive/domain/user/repository/RoleRepository.java
- src/main/java/kr/sparta/rchive/domain/user/service/RoleService.java
> [#196] Role: 신청 결과 쿼리문 수정

- src/main/java/kr/sparta/rchive/domain/backoffice/controller/BackofficeController.java
- src/main/java/kr/sparta/rchive/domain/backoffice/respoonse/BackofficeResponseCode.java
- src/main/java/kr/sparta/rchive/domain/bookmark/service/BookmarkService.java
- src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
- src/main/java/kr/sparta/rchive/domain/core/service/UserTrackRoleCoreService.java
- src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
- src/main/java/kr/sparta/rchive/domain/post/exception/PostExceptionCode.java
- src/main/java/kr/sparta/rchive/domain/post/service/TagService.java
- src/main/java/kr/sparta/rchive/domain/user/entity/Track.java
- src/main/java/kr/sparta/rchive/domain/user/service/TrackService.java
- src/main/java/kr/sparta/rchive/global/s3/exception/S3ExceptionCode.java
> [#195] BackOffice: 트랙의 열람 권한 거절하는 기능 추가

- src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
- src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
- src/main/java/kr/sparta/rchive/domain/post/enums/PostSearchTypeEnum.java
- src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustom.java
- src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustomImpl.java
- src/main/java/kr/sparta/rchive/domain/post/repository/TagRepository.java
- src/main/java/kr/sparta/rchive/domain/post/repository/TutorRepository.java
- src/main/java/kr/sparta/rchive/domain/post/repository/TutorRepositoryCustom.java
- src/main/java/kr/sparta/rchive/domain/post/repository/TutorRepositoryCustomImpl.java
- src/main/java/kr/sparta/rchive/domain/post/service/PostService.java
- src/main/java/kr/sparta/rchive/domain/post/service/TagService.java
- src/main/java/kr/sparta/rchive/domain/post/service/TutorService.java
> [#208] Post: 회의 후 post 검색 및 튜터 검색 기능 수정

- src/main/java/kr/sparta/rchive/domain/core/service/UserTrackRoleCoreService.java
- src/main/java/kr/sparta/rchive/global/redis/RedisService.java
> [#213] Role: 현재 권한 확인 로직 추가

- src/main/java/kr/sparta/rchive/domain/comment/dto/CommentRes.java
- src/main/java/kr/sparta/rchive/domain/comment/dto/CommentUserInfo.java
- src/main/java/kr/sparta/rchive/domain/comment/dto/response/CommentGetRes.java
- src/main/java/kr/sparta/rchive/domain/comment/entity/Comment.java
- src/main/java/kr/sparta/rchive/domain/comment/repository/CommentRepository.java
- src/main/java/kr/sparta/rchive/domain/comment/repository/CommentRepositoryCustom.java
- src/main/java/kr/sparta/rchive/domain/comment/repository/CommentRepositoryCustomImpl.java
- src/main/java/kr/sparta/rchive/domain/comment/service/CommentService.java
- src/main/java/kr/sparta/rchive/domain/core/service/PostCommentCoreService.java
- src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
- src/main/java/kr/sparta/rchive/domain/post/repository/TutorRepositoryCustomImpl.java
- src/main/java/kr/sparta/rchive/domain/post/response/PostResponseCode.java
> [#218] Comment: 게시물의 부모 댓글 조회하는 기능 추가

- src/main/java/kr/sparta/rchive/domain/comment/dto/CommentUserInfo.java
- src/main/java/kr/sparta/rchive/domain/comment/dto/response/CommentGetRes.java
- src/main/java/kr/sparta/rchive/domain/comment/entity/Comment.java
- src/main/java/kr/sparta/rchive/domain/comment/repository/CommentRepository.java
- src/main/java/kr/sparta/rchive/domain/comment/repository/CommentRepositoryCustom.java
- src/main/java/kr/sparta/rchive/domain/comment/repository/CommentRepositoryCustomImpl.java
- src/main/java/kr/sparta/rchive/domain/comment/service/CommentService.java
- src/main/java/kr/sparta/rchive/domain/core/service/PostCommentCoreService.java
- src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
- src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
- src/main/java/kr/sparta/rchive/domain/post/dto/response/PostGetSinglePostRes.java
- src/main/java/kr/sparta/rchive/domain/post/entity/Post.java
- src/main/java/kr/sparta/rchive/domain/post/repository/TutorRepositoryCustomImpl.java
- src/main/java/kr/sparta/rchive/domain/post/response/PostResponseCode.java
- src/main/java/kr/sparta/rchive/domain/post/service/PostService.java
> [#216] Comment: 댓글 삭제하는 기능 추가

- src/main/java/kr/sparta/rchive/domain/backoffice/controller/BackofficeController.java
- src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
- src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustom.java
- src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustomImpl.java
- src/main/java/kr/sparta/rchive/domain/post/service/PostService.java
> [#222] BackOffice : 프론트 개발 중 수정사항 발생 수정 완료

- src/main/java/kr/sparta/rchive/global/execption/ExceptionController.java
- src/main/java/kr/sparta/rchive/global/s3/controller/S3ImageController.java
- src/main/java/kr/sparta/rchive/global/s3/exception/statement/DeleteThumbnailException.java
- src/main/java/kr/sparta/rchive/global/s3/exception/statement/UploadThumbnailException.java
> [#238] Swagger: S3 예외 명세서 정리

- src/main/java/kr/sparta/rchive/domain/backoffice/controller/BackofficeController.java
- src/main/java/kr/sparta/rchive/domain/backoffice/exception/GetLastSelectRoleBackOfficeException.java
- src/main/java/kr/sparta/rchive/domain/backoffice/exception/GetProfileBackOfficeException.java
- src/main/java/kr/sparta/rchive/domain/backoffice/exception/GetTrackRoleRequestCount.java
- src/main/java/kr/sparta/rchive/domain/backoffice/exception/GetUserTrackRoleRquestListException.java
- src/main/java/kr/sparta/rchive/domain/backoffice/exception/SearchPostInBackOfficeException.java
- src/main/java/kr/sparta/rchive/domain/backoffice/exception/UserTrackPermissionException.java
- src/main/java/kr/sparta/rchive/domain/backoffice/exception/UserTrackRejectionException.java
- src/main/java/kr/sparta/rchive/domain/backoffice/exception/UserTrackRoleApproveException.java
- src/main/java/kr/sparta/rchive/domain/backoffice/exception/UserTrackRoleRejectException.java
- src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
- src/main/java/kr/sparta/rchive/domain/post/exception/statement/ClosePostException.java
- src/main/java/kr/sparta/rchive/domain/post/exception/statement/CreateBookmarkException.java
- src/main/java/kr/sparta/rchive/domain/post/exception/statement/CreateCommentException.java
- src/main/java/kr/sparta/rchive/domain/post/exception/statement/CreatePostException.java
- src/main/java/kr/sparta/rchive/domain/post/exception/statement/CreateTagException.java
- src/main/java/kr/sparta/rchive/domain/post/exception/statement/DeleteBookmarkException.java
- src/main/java/kr/sparta/rchive/domain/post/exception/statement/DeleteCommentException.java
- src/main/java/kr/sparta/rchive/domain/post/exception/statement/DeletePostException.java
- src/main/java/kr/sparta/rchive/domain/post/exception/statement/GetPostCategoryException.java
- src/main/java/kr/sparta/rchive/domain/post/exception/statement/GetPostException.java
- src/main/java/kr/sparta/rchive/domain/post/exception/statement/OpenPostException.java
- src/main/java/kr/sparta/rchive/domain/post/exception/statement/SearchPostByTagException.java
- src/main/java/kr/sparta/rchive/domain/post/exception/statement/SearchPostException.java
- src/main/java/kr/sparta/rchive/domain/post/exception/statement/SearchTutorException.java
- src/main/java/kr/sparta/rchive/domain/post/exception/statement/UpdatePostException.java
- src/main/java/kr/sparta/rchive/global/execption/ExceptionController.java
- src/main/java/kr/sparta/rchive/global/s3/controller/S3ImageController.java
- src/main/java/kr/sparta/rchive/global/s3/exception/statement/DeleteThumbnailException.java
- src/main/java/kr/sparta/rchive/global/s3/exception/statement/UploadThumbnailException.java
> [#234] Swagger: Post 예외 명세서 정리

- src/main/java/kr/sparta/rchive/domain/comment/repository/CommentRepository.java
- src/main/java/kr/sparta/rchive/domain/comment/service/CommentService.java
- src/main/java/kr/sparta/rchive/domain/core/service/PostCommentCoreService.java
- src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
- src/main/java/kr/sparta/rchive/domain/post/response/PostResponseCode.java
> [#226] Comment: 댓글의 대댓글 조회하는 기능 추가

- src/main/java/kr/sparta/rchive/global/config/WebMvcConfig.java
> [#202] CICD: CORS 에러

- src/main/java/kr/sparta/rchive/domain/user/enums/TrackNameEnum.java
> [#246] Track: TrackNameEnum 변경

- src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
- src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
- src/main/java/kr/sparta/rchive/domain/post/dto/response/PostGetRecentKeywordRes.java
- src/main/java/kr/sparta/rchive/domain/post/dto/response/PostSearchBackOfficeRes.java
- src/main/java/kr/sparta/rchive/domain/post/response/PostResponseCode.java
- src/main/java/kr/sparta/rchive/global/redis/RedisService.java
- src/main/java/kr/sparta/rchive/global/redis/RedisUtil.java
> [#249] 유저의 최근 검색 기록 가져오는 기능 추가

- .github/workflows/cicd-dev.yml
- .github/workflows/cicd-prod.yml
> [#202] CICD: cicd 수정

- src/main/java/kr/sparta/rchive/global/config/SwaggerConfig.java
- src/main/java/kr/sparta/rchive/global/execption/ExceptionController.java
- src/main/java/kr/sparta/rchive/global/security/LoginFilter.java
> [#259] API: url 수정

- src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
- src/main/java/kr/sparta/rchive/global/security/JwtUtil.java
- src/main/java/kr/sparta/rchive/global/security/LoginFilter.java
> [#165] HOTFIX: 리프레시토큰 set-cookie 오류

- src/main/java/kr/sparta/rchive/global/security/JwtUtil.java
프론트 로그인 테스트를 위한 accessToken과 refreshToken 시간 변경
> [#269] JWT: 프론트 로그인 테스트를 위한 accessToken과 refreshToken 시간 변경

- src/main/java/kr/sparta/rchive/global/config/WebSecurityConfig.java
> [#271] Security: reissue 권한 변경

- src/main/java/kr/sparta/rchive/global/security/JwtUtil.java
> [#275] Token: 프론트 요청으로 Refresh Token 시간 변견

- src/main/java/kr/sparta/rchive/domain/user/controller/UserController.java
- src/main/java/kr/sparta/rchive/domain/user/response/UserResponseCode.java
- src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
- src/main/java/kr/sparta/rchive/global/security/JwtAuthorizationFilter.java
Access Token 만료 여부 조회하는 api 추가
> [#277] User: Access Token 만료 여부 조회하는 api 추가

- src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
- src/main/java/kr/sparta/rchive/domain/post/exception/statement/DeleteRecentSearchKeywordException.java
- src/main/java/kr/sparta/rchive/domain/post/exception/statement/GetRecentSearchKeywordException.java
- src/main/java/kr/sparta/rchive/domain/post/exception/statement/SaveRecentSearchKeywordException.java
- src/main/java/kr/sparta/rchive/domain/user/controller/UserController.java
- src/main/java/kr/sparta/rchive/domain/user/response/UserResponseCode.java
- src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
- src/main/java/kr/sparta/rchive/global/security/JwtAuthorizationFilter.java
> [#273] Swagger: 추가 API로 인해 추가 된 예외 명세서 정리

- src/main/java/kr/sparta/rchive/domain/bookmark/repository/BookmarkRepositoryCustom.java
- src/main/java/kr/sparta/rchive/domain/bookmark/repository/BookmarkRepositoryCustomImpl.java
- src/main/java/kr/sparta/rchive/domain/bookmark/service/BookmarkService.java
- src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
- src/main/java/kr/sparta/rchive/domain/post/dto/response/PostRes.java
- src/main/java/kr/sparta/rchive/domain/post/exception/statement/DeleteRecentSearchKeywordException.java
- src/main/java/kr/sparta/rchive/domain/post/exception/statement/GetRecentSearchKeywordException.java
- src/main/java/kr/sparta/rchive/domain/post/exception/statement/SaveRecentSearchKeywordException.java
- src/main/java/kr/sparta/rchive/domain/user/controller/ProfileController.java
- src/main/java/kr/sparta/rchive/domain/user/controller/UserController.java
- src/main/java/kr/sparta/rchive/domain/user/response/ProfileResponseCode.java
- src/main/java/kr/sparta/rchive/domain/user/response/UserResponseCode.java
- src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
- src/main/java/kr/sparta/rchive/global/security/JwtAuthorizationFilter.java
> [#267] Profile: 자신이 북마크한 게시물들 검색할 수 있는 기능 추가

- src/main/java/kr/sparta/rchive/domain/bookmark/repository/BookmarkRepositoryCustom.java
- src/main/java/kr/sparta/rchive/domain/bookmark/repository/BookmarkRepositoryCustomImpl.java
- src/main/java/kr/sparta/rchive/domain/bookmark/service/BookmarkService.java
- src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
- src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
- src/main/java/kr/sparta/rchive/domain/post/dto/response/PostRes.java
- src/main/java/kr/sparta/rchive/domain/post/exception/statement/DeleteRecentSearchKeywordException.java
- src/main/java/kr/sparta/rchive/domain/post/exception/statement/GetRecentSearchKeywordException.java
- src/main/java/kr/sparta/rchive/domain/post/exception/statement/SaveRecentSearchKeywordException.java
- src/main/java/kr/sparta/rchive/domain/post/response/PostResponseCode.java
- src/main/java/kr/sparta/rchive/domain/user/controller/ProfileController.java
- src/main/java/kr/sparta/rchive/domain/user/controller/UserController.java
- src/main/java/kr/sparta/rchive/domain/user/response/ProfileResponseCode.java
- src/main/java/kr/sparta/rchive/domain/user/response/UserResponseCode.java
- src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
- src/main/java/kr/sparta/rchive/global/redis/RedisService.java
- src/main/java/kr/sparta/rchive/global/redis/RedisUtil.java
- src/main/java/kr/sparta/rchive/global/security/JwtAuthorizationFilter.java
> [#265] 최근 검색한 기록 삭제하는 기능 추가

- src/main/java/kr/sparta/rchive/global/security/JwtUtil.java
> [#279] Token: Access Token 시간 변경

- src/main/java/kr/sparta/rchive/domain/user/repository/RoleRepositoryCustomImpl.java
> [#281] Role: APM이 권한 신청한 인원 카운트하는 로직 수정

- src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
> [#283] test: 프엔과 로그인 테스트

- src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
> [#283] test: 프론트와 로그인 테스트

- src/main/java/kr/sparta/rchive/domain/backoffice/controller/BackofficeController.java
- src/main/java/kr/sparta/rchive/domain/core/service/UserTrackRoleCoreService.java
- src/main/java/kr/sparta/rchive/domain/user/repository/RoleRepositoryCustom.java
- src/main/java/kr/sparta/rchive/domain/user/repository/RoleRepositoryCustomImpl.java
- src/main/java/kr/sparta/rchive/domain/user/service/RoleService.java
> [#285] BackOffice: 백오피스 권한 요청 조회 기능 수정

- src/main/java/kr/sparta/rchive/global/security/JwtUtil.java
> [#283] test: 로그인 테스트

- .github/workflows/ci-dev.yml
- .github/workflows/ci-prod.yml
- .github/workflows/cicd-dev.yml
- .github/workflows/cicd-prod.yml
- src/main/java/kr/sparta/rchive/domain/user/controller/UserController.java
- src/main/java/kr/sparta/rchive/domain/user/dto/request/AuthPhoneReq.java
- src/main/java/kr/sparta/rchive/domain/user/response/UserResponseCode.java
- src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
- src/main/java/kr/sparta/rchive/global/config/RestTemplateConfig.java
- src/main/java/kr/sparta/rchive/global/redis/RedisService.java
- src/main/resources/application-dev.yml
- src/main/resources/application-prod.yml
- src/main/resources/application-test.yml
> [#288] User: 휴대폰 인증 전송

- src/main/java/kr/sparta/rchive/domain/backoffice/controller/BackofficeController.java
- src/main/java/kr/sparta/rchive/domain/backoffice/respoonse/BackofficeResponseCode.java
- src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
- src/main/java/kr/sparta/rchive/domain/post/dto/response/PostModifyPreviewRes.java
- src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustom.java
- src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustomImpl.java
- src/main/java/kr/sparta/rchive/domain/post/service/PostService.java
백오피스에서 게시물 수정 시 기존 게시물 내용 조회하는 기능 추가
> [#290] BackOffice: 백오피스에서 게시물 수정 시 기존 게시물 내용 조회하는 기능 추가

- src/main/java/kr/sparta/rchive/domain/user/controller/UserController.java
- src/main/java/kr/sparta/rchive/domain/user/dto/request/AuthPhoneValidReq.java
- src/main/java/kr/sparta/rchive/domain/user/exception/UserExceptionCode.java
- src/main/java/kr/sparta/rchive/domain/user/response/UserResponseCode.java
- src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
> [#293] User: 휴대폰 인증 확인

- src/main/java/kr/sparta/rchive/domain/user/controller/UserController.java
- src/main/java/kr/sparta/rchive/domain/user/dto/request/FindEmailReq.java
- src/main/java/kr/sparta/rchive/domain/user/dto/response/FindEmailRes.java
- src/main/java/kr/sparta/rchive/domain/user/exception/UserExceptionCode.java
- src/main/java/kr/sparta/rchive/domain/user/repository/UserRepository.java
- src/main/java/kr/sparta/rchive/domain/user/response/UserResponseCode.java
- src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
> [#295] User: 이메일 찾기

- src/main/java/kr/sparta/rchive/domain/user/controller/UserController.java
- src/main/java/kr/sparta/rchive/domain/user/dto/request/FindPasswordReq.java
- src/main/java/kr/sparta/rchive/domain/user/repository/UserRepository.java
- src/main/java/kr/sparta/rchive/domain/user/response/UserResponseCode.java
- src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
> [#296] User: 비밀번호 찾기

- src/main/java/kr/sparta/rchive/domain/user/controller/UserController.java
- src/main/java/kr/sparta/rchive/domain/user/dto/request/UserFindEmailReq.java
- src/main/java/kr/sparta/rchive/domain/user/dto/request/UserFindPasswordReq.java
- src/main/java/kr/sparta/rchive/domain/user/dto/request/UserFindPasswordUpdateReq.java
- src/main/java/kr/sparta/rchive/domain/user/repository/UserRepository.java
- src/main/java/kr/sparta/rchive/domain/user/response/UserResponseCode.java
- src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
> [#297] User: 비밀번호 찾기 후 변경

- src/main/java/kr/sparta/rchive/domain/core/service/UserTrackRoleCoreService.java
- src/main/java/kr/sparta/rchive/domain/user/repository/RoleRepository.java
- src/main/java/kr/sparta/rchive/domain/user/service/RoleService.java
> [#305] refactor(Role): 기존 apm이 새로운 트랙의 apm으로 변경될 시, 기존의 권한 삭제

- src/main/java/kr/sparta/rchive/domain/comment/dto/response/CommentProfileRes.java
- src/main/java/kr/sparta/rchive/domain/comment/repository/CommentRepositoryCustom.java
- src/main/java/kr/sparta/rchive/domain/comment/repository/CommentRepositoryCustomImpl.java
- src/main/java/kr/sparta/rchive/domain/comment/service/CommentService.java
- src/main/java/kr/sparta/rchive/domain/user/controller/ProfileController.java
- src/main/java/kr/sparta/rchive/domain/user/response/ProfileResponseCode.java
> [#306] Profile: 자신이 작성한 댓글 프로필에서 조회하는 기능 추가

- src/main/java/kr/sparta/rchive/domain/user/controller/UserController.java
- src/main/java/kr/sparta/rchive/domain/user/dto/request/UserFindPasswordCheckEmailReq.java
- src/main/java/kr/sparta/rchive/domain/user/dto/request/UserFindPasswordCheckPhoneReq.java
- src/main/java/kr/sparta/rchive/domain/user/repository/UserRepository.java
- src/main/java/kr/sparta/rchive/domain/user/response/UserResponseCode.java
- src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
> [#308] User: 비밀번호 찾기 수정

- src/main/java/kr/sparta/rchive/domain/backoffice/controller/BackofficeController.java
- src/main/java/kr/sparta/rchive/domain/core/service/UserTrackRoleCoreService.java
> [#313] BackOffice: 백오피스 권한 관련 수정

- .github/workflows/ci-dev.yml
- .github/workflows/ci-prod.yml
- .github/workflows/cicd-dev.yml
- .github/workflows/cicd-prod.yml
> [#315] CICD: 성능개선

- .github/workflows/cicd-dev.yml
> [#315] CICD: 성능 개선

- src/main/java/kr/sparta/rchive/domain/core/service/UserTrackRoleCoreService.java
- src/main/java/kr/sparta/rchive/domain/user/controller/ProfileController.java
- src/main/java/kr/sparta/rchive/domain/user/dto/request/ProfileUpdateNicknameReq.java
- src/main/java/kr/sparta/rchive/domain/user/dto/request/ProfileUpdatePasswordReq.java
- src/main/java/kr/sparta/rchive/domain/user/dto/request/ProfileUpdateProfileImgReq.java
- src/main/java/kr/sparta/rchive/domain/user/entity/User.java
- src/main/java/kr/sparta/rchive/domain/user/exception/UserExceptionCode.java
- src/main/java/kr/sparta/rchive/domain/user/response/ProfileResponseCode.java
- src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
> [#324] Refactor: 로직 수정

- src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
- src/main/java/kr/sparta/rchive/domain/post/dto/request/PostOpenCloseReq.java
- src/main/java/kr/sparta/rchive/domain/post/dto/request/PostUpdateReq.java
- src/test/java/kr/sparta/rchive/domain/post/controller/PostControllerTestForPM.java
PM과 관련된 PostController 테스트 코드 작성
> [#312] Test: PM과 관련된 PostController 테스트 코드 작성

- src/main/java/kr/sparta/rchive/global/config/WebMvcConfig.java
> [#331] CORS: 서브도메인 수정

- src/main/java/kr/sparta/rchive/global/security/JwtUtil.java
> [#333] test: 프론트엔드 테스트

- src/main/java/kr/sparta/rchive/domain/user/dto/request/UserSignupReq.java
- src/main/java/kr/sparta/rchive/domain/user/entity/User.java
- src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
> [#333] User: signup 수정

- src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
> [#333] Test: 로그인 테스트

- src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustomImpl.java
백오피스 게시물 검색 시 삭제된 게시물 보이지 않도록 변경
> [#338] BackOffice: 백오피스 게시물 검색 시 삭제된 게시물 보이지 않도록 변경

- .github/workflows/cicd-dev.yml
> [#344] CICD: 서버 에러로 dev cd 중지

- .github/workflows/cicd-dev.yml
> [#344] CICD: 서버 에러

- src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
- src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
- src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustom.java
- src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustomImpl.java
- src/main/java/kr/sparta/rchive/domain/post/service/PostService.java
- src/test/java/kr/sparta/rchive/domain/post/controller/PostControllerTestForUser.java
- src/test/java/kr/sparta/rchive/domain/post/service/PostServiceTest.java
> [#345] Post: 게시물 카테고리 조회 시 조건 변경

- src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
- src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
- src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustom.java
- src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustomImpl.java
- src/main/java/kr/sparta/rchive/domain/post/service/PostService.java
- src/test/java/kr/sparta/rchive/domain/post/controller/PostControllerTestForUser.java
- src/test/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustomImplTest.java
- src/test/java/kr/sparta/rchive/domain/post/repository/PostRepositoryTest.java
- src/test/java/kr/sparta/rchive/domain/post/service/PostServiceTest.java
- src/test/java/kr/sparta/rchive/test/PostTest.java
> [#341] Test: PostRepository 테스트 코드 작성 

- src/main/java/kr/sparta/rchive/domain/core/service/UserTrackRoleCoreService.java
- src/main/java/kr/sparta/rchive/domain/user/controller/RoleController.java
- src/main/java/kr/sparta/rchive/domain/user/dto/response/RoleGetMyRoleRes.java
- src/main/java/kr/sparta/rchive/domain/user/repository/TrackRepository.java
> [#349] Role: 권한 수정

- src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
- src/main/java/kr/sparta/rchive/domain/user/service/RoleService.java
- src/test/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustomImplTest.java
- src/test/java/kr/sparta/rchive/domain/post/repository/PostRepositoryTest.java
PostRepositoryCustomImpl 테스트 코드 추가
튜터 검색 로직 수정
> [#350] Test: PostRepositoryCustomImpl 테스트 코드 추가 및 로직 수정

- src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustomImpl.java
- src/main/java/kr/sparta/rchive/global/security/JwtUtil.java
- src/test/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustomImplTest.java
PostCustomImplTest 추가 및 액세스 토큰 시간 변경
> [#350] Test: PostCustomImplTest 추가 및 액세스 토큰 시간 변경

- src/main/java/kr/sparta/rchive/domain/user/dto/request/ProfileUpdateNicknameReq.java
- src/main/java/kr/sparta/rchive/domain/user/dto/request/UserSignupReq.java
- src/main/java/kr/sparta/rchive/domain/user/entity/User.java
> [#352] User: 닉네임 규정 변경

- src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
- src/main/java/kr/sparta/rchive/domain/post/dto/response/PostGetSinglePostRes.java
> [#350] Post: 프론트 요청으로 response 변경

- src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
- src/main/java/kr/sparta/rchive/domain/post/dto/response/PostGetSinglePostRes.java
> [#350] Post: 프론트 요청으로 로직 변경

- src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustomImpl.java
- src/test/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustomImplTest.java
PostRepositoryCustomImpl 테스트 코드 작성
> [#350] Test: PostRepositoryCustomImpl 테스트 코드 작성

- src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
- src/main/java/kr/sparta/rchive/domain/post/repository/TutorRepositoryCustomImpl.java
- src/test/java/kr/sparta/rchive/domain/core/service/PostTagCoreServiceTest.java
- src/test/java/kr/sparta/rchive/test/PostTagTest.java
- src/test/java/kr/sparta/rchive/test/RoleTest.java
PostCoreService 테스트 코드 추가 및 튜터 정렬 방식 설정
> [#361] Post: PostCoreService 테스트 코드 추가 및 튜터 정렬 방식 설정

- src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
- src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
- src/main/java/kr/sparta/rchive/domain/post/dto/request/DeleteThumbnailReq.java
- src/main/java/kr/sparta/rchive/domain/post/entity/Post.java
- src/main/java/kr/sparta/rchive/domain/post/response/PostResponseCode.java
- src/main/java/kr/sparta/rchive/domain/post/service/PostService.java
게시물 thumbnail을 삭제할 때 db에도 반영되는 로직 추가
> [#365] Post: 게시물 thumbnail을 삭제할 때 db에도 반영되는 로직 추가

- src/main/java/kr/sparta/rchive/domain/post/entity/Post.java
Post 클래스에 thumbnail 삭제 요청 시 db에서 삭제되게 하는 로직 수정
> [#365] refactor(post): Post 클래스에 thumbnail 삭제 요청 시 db에서 삭제되게 하는 로직 수정

- src/main/java/kr/sparta/rchive/domain/core/service/UserTrackRoleCoreService.java
- src/main/java/kr/sparta/rchive/domain/user/dto/TrackNameInfo.java
- src/main/java/kr/sparta/rchive/domain/user/dto/response/RoleGetLastSelectRoleRes.java
- src/main/java/kr/sparta/rchive/domain/user/dto/response/RoleGetTrackNameListRes.java
- src/main/java/kr/sparta/rchive/domain/user/dto/response/RoleRes.java
- src/main/java/kr/sparta/rchive/domain/user/dto/response/UserRes.java
- src/main/java/kr/sparta/rchive/domain/user/enums/TrackNameEnum.java
- src/main/java/kr/sparta/rchive/domain/user/enums/UserRoleEnum.java
- src/main/java/kr/sparta/rchive/domain/user/service/TrackService.java
> [#370] Track: TrackNameEnum Response 변경

- src/main/java/kr/sparta/rchive/domain/bookmark/service/BookmarkService.java
- src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
- src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
- src/main/java/kr/sparta/rchive/domain/post/dto/PostTypeInfo.java
- src/main/java/kr/sparta/rchive/domain/post/dto/request/DeleteThumbnailReq.java
- src/main/java/kr/sparta/rchive/domain/post/dto/response/PostGetPostTypeRes.java
- src/main/java/kr/sparta/rchive/domain/post/dto/response/PostGetRes.java
- src/main/java/kr/sparta/rchive/domain/post/dto/response/PostGetSinglePostRes.java
- src/main/java/kr/sparta/rchive/domain/post/dto/response/PostModifyPreviewRes.java
- src/main/java/kr/sparta/rchive/domain/post/dto/response/PostRes.java
- src/main/java/kr/sparta/rchive/domain/post/dto/response/PostSearchBackOfficeRes.java
- src/main/java/kr/sparta/rchive/domain/post/enums/PostTypeEnum.java
- src/main/java/kr/sparta/rchive/domain/post/response/PostResponseCode.java
- src/main/java/kr/sparta/rchive/domain/post/service/PostService.java
- src/test/java/kr/sparta/rchive/domain/core/service/PostTagCoreServiceTest.java
- src/test/java/kr/sparta/rchive/domain/post/controller/PostControllerTestForPM.java
- src/test/java/kr/sparta/rchive/domain/post/controller/PostControllerTestForUser.java
- src/test/java/kr/sparta/rchive/test/RoleTest.java
- src/test/java/kr/sparta/rchive/test/TrackTest.java
> [#371] Post: PostTypeEnum 한글화

- src/main/java/kr/sparta/rchive/domain/bookmark/service/BookmarkService.java
- src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
- src/main/java/kr/sparta/rchive/domain/core/service/UserTrackRoleCoreService.java
- src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
- src/main/java/kr/sparta/rchive/domain/post/dto/PostTypeInfo.java
- src/main/java/kr/sparta/rchive/domain/post/dto/request/DeleteThumbnailReq.java
- src/main/java/kr/sparta/rchive/domain/post/dto/response/PostGetPostTypeRes.java
- src/main/java/kr/sparta/rchive/domain/post/dto/response/PostGetRes.java
- src/main/java/kr/sparta/rchive/domain/post/dto/response/PostGetSinglePostRes.java
- src/main/java/kr/sparta/rchive/domain/post/dto/response/PostModifyPreviewRes.java
- src/main/java/kr/sparta/rchive/domain/post/dto/response/PostRes.java
- src/main/java/kr/sparta/rchive/domain/post/dto/response/PostSearchBackOfficeRes.java
- src/main/java/kr/sparta/rchive/domain/post/enums/PostTypeEnum.java
- src/main/java/kr/sparta/rchive/domain/post/response/PostResponseCode.java
- src/main/java/kr/sparta/rchive/domain/post/service/PostService.java
- src/main/java/kr/sparta/rchive/domain/user/dto/TrackNameInfo.java
- src/main/java/kr/sparta/rchive/domain/user/dto/response/RoleGetLastSelectRoleRes.java
- src/main/java/kr/sparta/rchive/domain/user/dto/response/RoleGetTrackNameListRes.java
- src/main/java/kr/sparta/rchive/domain/user/dto/response/RoleRes.java
- src/main/java/kr/sparta/rchive/domain/user/dto/response/UserRes.java
- src/main/java/kr/sparta/rchive/domain/user/enums/TrackNameEnum.java
- src/main/java/kr/sparta/rchive/domain/user/enums/UserRoleEnum.java
- src/main/java/kr/sparta/rchive/domain/user/service/TrackService.java
- src/test/java/kr/sparta/rchive/domain/core/service/PostTagCoreServiceTest.java
- src/test/java/kr/sparta/rchive/domain/post/controller/PostControllerTestForPM.java
- src/test/java/kr/sparta/rchive/domain/post/controller/PostControllerTestForUser.java
- src/test/java/kr/sparta/rchive/test/RoleTest.java
- src/test/java/kr/sparta/rchive/test/TrackTest.java
> [#369] Refactor: Enum 구성 변경

- src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
- src/main/java/kr/sparta/rchive/domain/post/dto/response/PostGetPostTypeRes.java
- src/main/java/kr/sparta/rchive/domain/post/enums/PostTypeEnum.java
- src/main/java/kr/sparta/rchive/domain/post/service/PostService.java
- src/test/java/kr/sparta/rchive/domain/post/controller/PostControllerTestForUser.java
- src/test/java/kr/sparta/rchive/domain/post/service/PostServiceTest.java
> [#361] Post: PostType의 순서를 변경 및 테스트 추가

- src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
- src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustom.java
- src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustomImpl.java
- src/main/java/kr/sparta/rchive/domain/post/service/PostService.java
- src/test/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustomImplTest.java
- src/test/java/kr/sparta/rchive/domain/post/service/PostServiceTest.java
게시물 검색 시 태그 내용으로도 검색할 수 있도록 변경
> [#376] Post: 게시물 검색 시 태그 내용으로도 검색할 수 있도록 변경

- src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
- src/test/java/kr/sparta/rchive/domain/post/controller/PostControllerTestForUser.java
loginPeriod가 어색한 부분 selectPeriod로 변경
> [#382] Post: loginPeriod가 어색한 부분 selectPeriod로 변경

- src/main/java/kr/sparta/rchive/domain/user/service/RoleService.java
> [#384] Role: userTrackRoleApprove 수정

- src/main/java/kr/sparta/rchive/domain/user/dto/request/UserSignupReq.java
- src/main/java/kr/sparta/rchive/domain/user/entity/User.java
- src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
> [#388] User: 회원가입 할 때 닉네임 임의로 설정

- src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
- src/main/java/kr/sparta/rchive/domain/post/entity/Post.java
- src/test/java/kr/sparta/rchive/domain/core/service/PostTagCoreServiceTest.java
- src/test/java/kr/sparta/rchive/domain/post/controller/PostControllerTestForPM.java
- src/test/java/kr/sparta/rchive/test/PostTest.java
- src/test/java/kr/sparta/rchive/test/TrackTest.java
- src/test/java/kr/sparta/rchive/test/TutorTest.java
> [#361] Test: PostTagCoreService 테스트 코드 추가

- src/main/java/kr/sparta/rchive/domain/user/dto/request/AuthPhoneReq.java
- src/main/java/kr/sparta/rchive/domain/user/dto/request/AuthPhoneValidReq.java
- src/main/java/kr/sparta/rchive/domain/user/dto/request/ProfileUpdateNicknameReq.java
- src/main/java/kr/sparta/rchive/domain/user/dto/request/ProfileUpdatePasswordReq.java
- src/main/java/kr/sparta/rchive/domain/user/dto/request/ProfileUpdatePhoneReq.java
- src/main/java/kr/sparta/rchive/domain/user/dto/request/ProfileUpdateProfileImgReq.java
- src/main/java/kr/sparta/rchive/domain/user/dto/request/RoleReq.java
- src/main/java/kr/sparta/rchive/domain/user/dto/request/RoleRequestListReq.java
- src/main/java/kr/sparta/rchive/domain/user/dto/request/RoleRequestReq.java
- src/main/java/kr/sparta/rchive/domain/user/dto/request/UserFindEmailReq.java
- src/main/java/kr/sparta/rchive/domain/user/dto/request/UserFindPasswordCheckEmailReq.java
- src/main/java/kr/sparta/rchive/domain/user/dto/request/UserFindPasswordCheckPhoneReq.java
- src/main/java/kr/sparta/rchive/domain/user/dto/request/UserFindPasswordUpdateReq.java
- src/main/java/kr/sparta/rchive/domain/user/dto/request/UserLoginReq.java
- src/main/java/kr/sparta/rchive/domain/user/dto/request/UserSignupReq.java
> [#379] User: Swagger DTO예시

- src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
- src/main/java/kr/sparta/rchive/domain/post/service/PostTagService.java
- src/test/java/kr/sparta/rchive/domain/post/service/PostTagServiceTest.java
- src/test/java/kr/sparta/rchive/test/PostTagTest.java
> [#392] Test: postTagService 테스트 코드 추가

- src/main/java/kr/sparta/rchive/domain/post/service/TagService.java
- src/test/java/kr/sparta/rchive/domain/post/service/TagServiceTest.java
> [#394] Test: TagService 테스트 코드 작성

- src/main/java/kr/sparta/rchive/domain/bookmark/service/BookmarkService.java
- src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
- src/main/java/kr/sparta/rchive/domain/post/dto/request/TagCreateReq.java
- src/main/java/kr/sparta/rchive/domain/post/dto/response/TagCreateRes.java
- src/main/java/kr/sparta/rchive/domain/post/service/TagService.java
- src/main/java/kr/sparta/rchive/domain/user/controller/ProfileController.java
- src/test/java/kr/sparta/rchive/domain/post/controller/PostControllerTestForPM.java
- src/test/java/kr/sparta/rchive/domain/post/service/TagServiceTest.java
태그 생성 로직 변경 및 북마크 목록 조회 시 북마크 표시 확인 가능하게 변경
> [#396] Post: 태그 생성 로직 변경 및 북마크 목록 조회 시 북마크 표시 확인 가능하게 변경

- src/main/java/kr/sparta/rchive/domain/user/controller/UserController.java
- src/main/java/kr/sparta/rchive/domain/user/dto/request/UserFindPasswordUpdateReq.java
- src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
- src/test/java/kr/sparta/rchive/domain/post/controller/PostControllerTestForPM.java
- src/test/java/kr/sparta/rchive/domain/user/controller/UserControllerTest.java
- src/test/java/kr/sparta/rchive/test/UserTest.java
> [#364] Test: UserController 테스트코드

- src/test/java/kr/sparta/rchive/domain/post/service/TutorServiceTest.java
> [#403] Test: TutorService 테스트 코드 작성

- src/main/java/kr/sparta/rchive/domain/comment/dto/request/CommentCreateReq.java
- src/test/java/kr/sparta/rchive/domain/core/service/PostTagCoreServiceTest.java
> [#381] Swagger: Comment Dto 예시 작성

- src/main/java/kr/sparta/rchive/domain/comment/dto/request/CommentCreateReq.java
- src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
- src/main/java/kr/sparta/rchive/domain/post/dto/request/DeleteThumbnailReq.java
- src/main/java/kr/sparta/rchive/domain/post/dto/request/PostCreateReq.java
- src/main/java/kr/sparta/rchive/domain/post/dto/request/PostOpenCloseReq.java
- src/main/java/kr/sparta/rchive/domain/post/dto/request/PostUpdateReq.java
- src/main/java/kr/sparta/rchive/domain/post/dto/request/RecentSearchKeywordReq.java
- src/main/java/kr/sparta/rchive/domain/post/dto/request/TagCreateReq.java
- src/main/java/kr/sparta/rchive/domain/user/controller/UserController.java
- src/main/java/kr/sparta/rchive/domain/user/dto/request/AuthPhoneReq.java
- src/main/java/kr/sparta/rchive/domain/user/dto/request/AuthPhoneValidReq.java
- src/main/java/kr/sparta/rchive/domain/user/dto/request/ProfileUpdateNicknameReq.java
- src/main/java/kr/sparta/rchive/domain/user/dto/request/ProfileUpdatePasswordReq.java
- src/main/java/kr/sparta/rchive/domain/user/dto/request/ProfileUpdatePhoneReq.java
- src/main/java/kr/sparta/rchive/domain/user/dto/request/ProfileUpdateProfileImgReq.java
- src/main/java/kr/sparta/rchive/domain/user/dto/request/RoleReq.java
- src/main/java/kr/sparta/rchive/domain/user/dto/request/RoleRequestListReq.java
- src/main/java/kr/sparta/rchive/domain/user/dto/request/RoleRequestReq.java
- src/main/java/kr/sparta/rchive/domain/user/dto/request/UserFindEmailReq.java
- src/main/java/kr/sparta/rchive/domain/user/dto/request/UserFindPasswordCheckEmailReq.java
- src/main/java/kr/sparta/rchive/domain/user/dto/request/UserFindPasswordCheckPhoneReq.java
- src/main/java/kr/sparta/rchive/domain/user/dto/request/UserFindPasswordUpdateReq.java
- src/main/java/kr/sparta/rchive/domain/user/dto/request/UserLoginReq.java
- src/main/java/kr/sparta/rchive/domain/user/dto/request/UserSignupReq.java
- src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
- src/test/java/kr/sparta/rchive/domain/core/service/PostTagCoreServiceTest.java
- src/test/java/kr/sparta/rchive/domain/post/controller/PostControllerTestForPM.java
- src/test/java/kr/sparta/rchive/domain/user/controller/UserControllerTest.java
- src/test/java/kr/sparta/rchive/test/UserTest.java
> [#380] Swagger: Post 관련 Dto 예시 작성

- src/test/java/kr/sparta/rchive/domain/post/service/PostServiceTest.java
> [#381] Post: 테스트 코드 수정

- src/main/java/kr/sparta/rchive/domain/post/service/TagService.java
태그 생성 시 띄어쓰기 제거 후 저장하는 방식으로 변경
> [#413] Tag: 태그 생성 시 띄어쓰기 제거 후 저장하는 방식으로 변경

- src/main/java/kr/sparta/rchive/domain/post/entity/Post.java
> [#416] Post: 링크 길이 변경

- src/main/java/kr/sparta/rchive/domain/post/service/TagService.java
> [#413] Tag: 태그 생성 시 공백 제거

- src/main/java/kr/sparta/rchive/domain/user/repository/RoleRepositoryCustomImpl.java
> [#419] Role: 출력 period 내림차순

- src/test/java/kr/sparta/rchive/domain/core/service/PostCommentCoreServiceTest.java
PostCommentCoreService 테스트 코드 추가
> [#423] Test: PostCommentCoreService 테스트 코드 추가

- src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
- src/main/java/kr/sparta/rchive/domain/post/dto/request/PostUpdateContentReq.java
- src/main/java/kr/sparta/rchive/domain/post/entity/Post.java
- src/main/java/kr/sparta/rchive/domain/post/response/PostResponseCode.java
- src/main/java/kr/sparta/rchive/domain/post/service/PostService.java
> [#426] Post: 게시물 내용 업데이트 기능 추가

- src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
> [#426] refactor(post): 게시물 내용 업데이트 operationId 오타 수정

- src/main/java/kr/sparta/rchive/global/redis/RedisService.java
- src/main/java/kr/sparta/rchive/global/security/JwtUtil.java
> [#429] User: 로그인 토큰 테스트

- src/main/java/kr/sparta/rchive/global/redis/RedisService.java
- src/main/java/kr/sparta/rchive/global/security/JwtUtil.java
> [#429] test: user login token time
